import { useState } from 'react';
import { supabase } from '@/lib/supabase';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { Printer, Calendar } from 'lucide-react';
import { toast } from 'sonner';
import { useProfile } from '@/hooks/useProfile';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ReportModal = ({ isOpen, onClose }: ReportModalProps) => {
  const { data: profile } = useProfile();
  const [loading, setLoading] = useState(false);
  const [selectedMonth, setSelectedMonth] = useState(new Date().toISOString().slice(0, 7)); // YYYY-MM
  const [reportData, setReportData] = useState<any>(null);

  const generateReport = async () => {
    if (!profile?.unit_id) return;
    setLoading(true);
    try {
      const startDate = `${selectedMonth}-01`;

      const { data, error } = await supabase.rpc('get_unit_monthly_report', {
        p_unit_id: profile.unit_id,
        p_month_start: startDate
      });

      if (error) throw error;
      setReportData(data);
    } catch (err: any) {
      console.error(err);
      toast.error("Failed to generate report");
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Generate Monthly Report">
      <div className="space-y-6 print:p-0">

        {/* CONTROLS */}
        <div className="flex gap-4 items-end bg-slate-50 p-4 rounded-xl border border-slate-100 print:hidden">
          <div className="flex-1">
            <label className="text-xs font-bold text-slate-500 uppercase mb-1 block">Select Month</label>
            <input
              type="month"
              className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-500"
              value={selectedMonth}
              onChange={(e) => {
                setReportData(null);
                setSelectedMonth(e.target.value);
              }}
            />
          </div>
          <Button onClick={generateReport} isLoading={loading}>
            Generate
          </Button>
        </div>

        {/* REPORT PREVIEW */}
        {reportData && (
          <div className="animate-in fade-in slide-in-from-bottom-4">
            <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm print:border-none print:shadow-none print:p-0">

              <div className="border-b border-slate-100 pb-4 mb-4 text-center">
                <h2 className="text-2xl font-bold text-slate-900 uppercase tracking-wide">Unit Monthly Report</h2>
                <p className="text-slate-500">{reportData.period}</p>
                <p className="text-xs text-slate-400 mt-1">Generated by {profile?.full_name}</p>
              </div>

              <div className="grid grid-cols-2 gap-6 mb-6">
                <div className="p-4 bg-blue-50 rounded-lg print:bg-transparent print:border print:border-slate-200">
                  <p className="text-xs font-bold text-blue-600 uppercase mb-1">Avg. Attendance</p>
                  <p className="text-2xl font-bold text-slate-900">{reportData.avg_attendance}</p>
                </div>
                <div className="p-4 bg-pink-50 rounded-lg print:bg-transparent print:border print:border-slate-200">
                  <p className="text-xs font-bold text-pink-600 uppercase mb-1">Souls Won</p>
                  <p className="text-2xl font-bold text-slate-900">{reportData.souls_won}</p>
                </div>
                <div className="p-4 bg-green-50 rounded-lg print:bg-transparent print:border print:border-slate-200">
                  <p className="text-xs font-bold text-green-600 uppercase mb-1">New Members</p>
                  <p className="text-2xl font-bold text-slate-900">{reportData.new_members}</p>
                </div>
                <div className="p-4 bg-amber-50 rounded-lg print:bg-transparent print:border print:border-slate-200">
                  <p className="text-xs font-bold text-amber-600 uppercase mb-1">Net Finance</p>
                  <p className={`text-2xl font-bold ${reportData.net_balance >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                    ₦{reportData.net_balance.toLocaleString()}
                  </p>
                </div>
              </div>

              <div className="flex justify-between text-sm text-slate-500 border-t border-slate-100 pt-4">
                <span>Total Income: <span className="font-bold text-slate-700">₦{reportData.total_income.toLocaleString()}</span></span>
                <span>Total Expense: <span className="font-bold text-slate-700">₦{reportData.total_expense.toLocaleString()}</span></span>
              </div>
            </div>

            <div className="flex justify-end gap-3 mt-6 print:hidden">
              <Button variant="outline" onClick={handlePrint}>
                <Printer className="mr-2 h-4 w-4" /> Print / Save PDF
              </Button>
            </div>
          </div>
        )}

        {!reportData && !loading && (
          <div className="text-center py-12 text-slate-400 print:hidden">
            <Calendar className="h-12 w-12 mx-auto mb-2 opacity-20" />
            <p>Select a month to view report.</p>
          </div>
        )}
      </div>
    </Modal>
  );
};